export const GET_MY_GROUPS = "GET_MY_GROUPS";
export const GET_MY_GROUPS_START = "GET_MY_GROUPS_START";
export const GET_MY_GROUPS_END = "GET_MY_GROUPS_END";
export const GET_MY_GROUPS_SUCCESS = "GET_MY_GROUPS_SUCCESS";
export const GET_MY_GROUPS_FAILED = "GET_MY_GROUPS_FAILED";

export const CREATE_GROUP_START = "CREATE_GROUP_START";
export const CREATE_GROUP_END = "CREATE_GROUP_END";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const GROUP_MESSAGES_CLEAR = "GROUP_MESSAGES_CLEAR";
export const GROUP_MESSAGES = "GROUP_MESSAGES";
export const GROUP_MESSAGES_START = "GROUP_MESSAGES_START";
export const GROUP_MESSAGES_END = "GROUP_MESSAGES_END";
export const GROUP_MESSAGES_SUCCESS = "GROUP_MESSAGES_SUCCESS";
export const GROUP_MESSAGES_FAILED = "GROUP_MESSAGES_FAILED";

export const GROUP_MESSAGES_STREAM = "GROUP_MESSAGES_STREAM";
export const GROUP_MESSAGES_STREAM_START = "GROUP_MESSAGES_STREAM_START";
export const GROUP_MESSAGES_STREAM_END = "GROUP_MESSAGES_STREAM_END";
export const GROUP_MESSAGES_STREAM_FAILED = "GROUP_MESSAGES_STREAM_FAILED";
