export const SIGN_IN_EMAIL = 'SIGN_IN_EMAIL';
export const SIGN_IN_EMAIL_START = 'SIGN_IN_EMAIL_START';
export const SIGN_IN_EMAIL_END = 'SIGN_IN_EMAIL_END';
export const SIGN_IN_EMAIL_SUCCESS = 'SIGN_IN_EMAIL_SUCCESS';
export const SIGN_IN_EMAIL_FAILED = 'SIGN_IN_EMAIL_FAILED';
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const LINKEDIN_SIGN_IN_START = 'LINKEDIN_SIGN_IN_START';
export const LINKEDIN_SIGN_IN_SUCCESS = 'LINKEDIN_SIGN_IN_SUCCESS';

export const UPDATE_ME_START = 'UPDATE_ME_START';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const UPDATE_ME_FAILED = 'UPDATE_ME_FAILED';

export const GET_MY_GROUPS = 'GET_MY_GROUPS';
export const GET_MY_GROUPS_START = 'GET_MY_GROUPS_START';
export const GET_MY_GROUPS_END = 'GET_MY_GROUPS_END';
export const GET_MY_GROUPS_SUCCESS = 'GET_MY_GROUPS_SUCCESS';
export const GET_MY_GROUPS_FAILED = 'GET_MY_GROUPS_FAILED';

export const GET_GROUPS_REQUESTS = 'GET_GROUPS_REQUESTS';
export const GET_GROUPS_REQUESTS_START = 'GET_GROUPS_REQUESTS_START';
export const GET_GROUPS_REQUESTS_END = 'GET_GROUPS_REQUESTS_END';
export const GET_GROUPS_REQUESTS_SUCCESS = 'GET_GROUPS_REQUESTS_SUCCESS';
export const GET_GROUPS_REQUESTS_FAILED = 'GET_GROUPS_REQUESTS_FAILED';

export const CREATE_GROUP_START = 'CREATE_GROUP_START';
export const CREATE_GROUP_END = 'CREATE_GROUP_END';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';

export const GROUP_MESSAGES_CLEAR = 'GROUP_MESSAGES_CLEAR';
export const GROUP_MESSAGES = 'GROUP_MESSAGES';
export const GROUP_MESSAGES_START = 'GROUP_MESSAGES_START';
export const GROUP_MESSAGES_END = 'GROUP_MESSAGES_END';
export const GROUP_MESSAGES_SUCCESS = 'GROUP_MESSAGES_SUCCESS';
export const GROUP_MESSAGES_FAILED = 'GROUP_MESSAGES_FAILED';

export const GROUP_MESSAGES_STREAM = 'GROUP_MESSAGES_STREAM';
export const GROUP_MESSAGES_STREAM_START = 'GROUP_MESSAGES_STREAM_START';
export const GROUP_MESSAGES_STREAM_END = 'GROUP_MESSAGES_STREAM_END';
export const GROUP_MESSAGES_STREAM_FAILED = 'GROUP_MESSAGES_STREAM_FAILED';

export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_START = 'GET_GROUP_START';
export const GET_GROUP_END = 'GET_GROUP_END';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILED = 'GET_GROUP_FAILED';

export const GET_GROUP_MEMBERS = 'GET_GROUP_MEMBERS';
export const GET_GROUP_MEMBERS_START = 'GET_GROUP_MEMBERS_START';
export const GET_GROUP_MEMBERS_END = 'GET_GROUP_MEMBERS_END';
export const GET_GROUP_MEMBERS_SUCCESS = 'GET_GROUP_MEMBERS_SUCCESS';
export const GET_GROUP_MEMBERS_FAILED = 'GET_GROUP_MEMBERS_FAILED';

export const GET_GROUP_MESSAGES = 'GET_GROUP_MESSAGES';
export const GET_GROUP_MESSAGES_START = 'GET_GROUP_MESSAGES_START';
export const GET_GROUP_MESSAGES_END = 'GET_GROUP_MESSAGES_END';
export const GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS';
export const GET_GROUP_MESSAGES_FAILED = 'GET_GROUP_MESSAGES_FAILED';

export const SEND_GROUP_MESSAGE_START = 'SEND_GROUP_MESSAGE_START';
export const SEND_GROUP_MESSAGE_END = 'SEND_GROUP_MESSAGE_END';
export const SEND_GROUP_MESSAGE_SUCCESS = 'SEND_GROUP_MESSAGE_SUCCESS';
export const SEND_GROUP_MESSAGE_FAILED = 'SEND_GROUP_MESSAGE_FAILED';

export const INVITE_MEMBER_START = 'INVITE_MEMBER_START';
export const INVITE_MEMBER_END = 'INVITE_MEMBER_END';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_FAILED = 'INVITE_MEMBER_FAILED';

export const CHANGE_GROUP_STATE_START = 'CHANGE_GROUP_STATE_START';
export const CHANGE_GROUP_STATE_END = 'CHANGE_GROUP_STATE_END';
export const CHANGE_GROUP_STATE_SUCCESS = 'CHANGE_GROUP_STATE_SUCCESS';
export const CHANGE_GROUP_STATE_FAILED = 'CHANGE_GROUP_STATE_FAILED';

export const CREATE_BLOG_POST_INITIATING = 'WRITE_POST_INITIATING';
export const CREATE_BLOG_POST_START = 'WRITE_POST_START';
export const CREATE_BLOG_POST_FAILED = 'WRITE_POST_SUCCESS';
export const CREATE_BLOG_POST_SUCCESS = 'WRITE_POST_FAILED';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_END = 'GET_POSTS_END';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const GET_QUESTIONS_START = 'GET_QUESTIONS_START';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED';

export const CREATE_QUESTION_START = 'CREATE_QUESTION_START';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILED = 'CREATE_QUESTION_FAILED';

export const GET_USER_SKILLS_START = 'GET_USER_SKILLS_START';
export const GET_USER_SKILLS_SUCCESS = 'GET_USER_SKILLS_SUCCESS';
export const GET_USER_SKILLS_FAILED = 'GET_USER_SKILLS_FAILED';

export const ADD_USER_SKILLS_START = 'ADD_USER_SKILLS_START';
export const ADD_USER_SKILLS_SUCCESS = 'ADD_USER_SKILLS_SUCCESS';
export const ADD_USER_SKILLS_FAILED = 'ADD_USER_SKILLS_FAILED';

export const DELETE_USER_SKILLS_START = 'DELETE_USER_SKILLS_START';
export const DELETE_USER_SKILLS_SUCCESS = 'DELETE_USER_SKILLS_SUCCESS';
export const DELETE_USER_SKILLS_FAILED = 'DELETE_USER_SKILLS_FAILED';
