export const GET_MY_GROUPS = "GET_MY_GROUPS";
export const GET_MY_GROUPS_START = "GET_MY_GROUPS_START";
export const GET_MY_GROUPS_END = "GET_MY_GROUPS_END";
export const GET_MY_GROUPS_SUCCESS = "GET_MY_GROUPS_SUCCESS";
export const GET_MY_GROUPS_FAILED = "GET_MY_GROUPS_FAILED";

export const CREATE_GROUP_START = "CREATE_GROUP_START";
export const CREATE_GROUP_END = "CREATE_GROUP_END";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const GROUP_MESSAGES_CLEAR = "GROUP_MESSAGES_CLEAR";
export const GROUP_MESSAGES = "GROUP_MESSAGES";
export const GROUP_MESSAGES_START = "GROUP_MESSAGES_START";
export const GROUP_MESSAGES_END = "GROUP_MESSAGES_END";
export const GROUP_MESSAGES_SUCCESS = "GROUP_MESSAGES_SUCCESS";
export const GROUP_MESSAGES_FAILED = "GROUP_MESSAGES_FAILED";

export const GROUP_MESSAGES_STREAM = "GROUP_MESSAGES_STREAM";
export const GROUP_MESSAGES_STREAM_START = "GROUP_MESSAGES_STREAM_START";
export const GROUP_MESSAGES_STREAM_END = "GROUP_MESSAGES_STREAM_END";
export const GROUP_MESSAGES_STREAM_FAILED = "GROUP_MESSAGES_STREAM_FAILED";

export const GET_GROUP = "GET_GROUP";
export const GET_GROUP_START = "GET_GROUP_START";
export const GET_GROUP_END = "GET_GROUP_END";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";
export const GET_GROUP_FAILED = "GET_GROUP_FAILED";

export const GET_GROUP_MEMBERS = "GET_GROUP_MEMBERS";
export const GET_GROUP_MEMBERS_START = "GET_GROUP_MEMBERS_START";
export const GET_GROUP_MEMBERS_END = "GET_GROUP_MEMBERS_END";
export const GET_GROUP_MEMBERS_SUCCESS = "GET_GROUP_MEMBERS_SUCCESS";
export const GET_GROUP_MEMBERS_FAILED = "GET_GROUP_MEMBERS_FAILED";

export const GET_GROUP_MESSAGES = "GET_GROUP_MESSAGES";
export const GET_GROUP_MESSAGES_START = "GET_GROUP_MESSAGES_START";
export const GET_GROUP_MESSAGES_END = "GET_GROUP_MESSAGES_END";
export const GET_GROUP_MESSAGES_SUCCESS = "GET_GROUP_MESSAGES_SUCCESS";
export const GET_GROUP_MESSAGES_FAILED = "GET_GROUP_MESSAGES_FAILED";

export const SEND_GROUP_MESSAGE_START = "SEND_GROUP_MESSAGE_START";
export const SEND_GROUP_MESSAGE_END = "SEND_GROUP_MESSAGE_END";
export const SEND_GROUP_MESSAGE_SUCCESS = "SEND_GROUP_MESSAGE_SUCCESS";
export const SEND_GROUP_MESSAGE_FAILED = "SEND_GROUP_MESSAGE_FAILED";
