export const REACT_APP_API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
export const REACT_APP_ACCESS_TOKEN_DURATION_HOURS =
  process.env.REACT_APP_ACCESS_TOKEN_DURATION_HOURS;
export const REACT_APP_GOOGLE_CLIENT_ID =
  process.env.REACT_APP_GOOGLE_CLIENT_ID;
