export const CREATE_QUESTION_START = 'CREATE_QUESTION_START';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILED = 'CREATE_QUESTION_FAILED';
export const CLEAR_CEATE_QESTION_STATE = "CLEAR_CEATE_QESTION_STATE";

export const GET_QUESTIONS_START = 'GET_QUESTIONS_START';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED';

export const CREATE_ANSWER_START = "CREATE_ANSWER_START";
export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAILED = "CREATE_ANSWER_FAILED";

export const GET_ANSWER_START = "GET_ANSWER_START";
export const GET_ANSWER_SUCCESS = "GET_ANSWER_SUCCESS";
export const GET_ANSWER_FAILED = "GET_ANSWER_FAILED";

export const GET_CREATE_ANSWER_START = "GET_CREATE_ANSWER_START";
export const GET_CREATE_ANSWER_SUCCESS = "GET_CREATE_ANSWER_SUCCESS";
export const GET_CREATE_ANSWER_FAILED = "GET_CREATE_ANSWER_FAILED";

export const GET_SINGLE_QUESTION_START = "GET_SINGLE_QUESTION_START";
export const GET_SINGLE_QUESTION_SUCCESS = "GET_SINGLE_QUESTION_SUCCESS";
export const GET_SINGLE_QUESTION_FAILED = "GET_SINGLE_QUESTION_FAILED";

