kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fior-app-dev
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: fior-app
        role: frontend
        env: production
    spec:
      containers:
        - name: frontend
          image: gcr.io/fior-app
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          env:
            - name: COMPONENT
              value: frontend
            - name: VERSION
              value: production
          ports:
            - name: frontend
              containerPort: 3000
