apiVersion: v1
kind: Service
metadata:
  labels:
    app: fior-app-canary
  name: fior-app-canary
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample
    role: frontend
    env: canary
  sessionAffinity: None
  type: LoadBalancer
