apiVersion: v1
kind: Service
metadata:
  labels:
    app: fior-app-dev
  name: fior-app-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample
    role: frontend
  sessionAffinity: None
  type: LoadBalancer
